-- MySQL Script generated by MySQL Workbench
-- Fri Apr  6 21:09:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ChemDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ChemDB` ;

-- -----------------------------------------------------
-- Schema ChemDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ChemDB` DEFAULT CHARACTER SET armscii8 ;
USE `ChemDB` ;

-- -----------------------------------------------------
-- Table `ChemDB`.`Assay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Assay` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Assay` (
  `aid` INT NULL DEFAULT NULL,
  `acid` INT NULL DEFAULT NULL,
  `aeid` INT NOT NULL,
  `asid` INT NULL DEFAULT NULL,
  `assay_source_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_source_long_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_source_desc` TEXT NULL DEFAULT NULL,
  `assay_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_desc` VARCHAR(255) NULL DEFAULT NULL,
  `timepoint_hr` INT NULL DEFAULT NULL,
  `organism_id` INT NULL DEFAULT NULL,
  `organism` VARCHAR(64) NULL DEFAULT NULL,
  `tissue` VARCHAR(64) NULL DEFAULT NULL,
  `cell_format` VARCHAR(64) NULL DEFAULT NULL,
  `cell_free_component_source` VARCHAR(255) NULL DEFAULT NULL,
  `cell_short_name` VARCHAR(64) NULL DEFAULT NULL,
  `cell_growth_mode` VARCHAR(64) NULL DEFAULT NULL,
  `assay_footprINT` VARCHAR(64) NULL DEFAULT NULL,
  `assay_format_type` VARCHAR(64) NULL DEFAULT NULL,
  `assay_format_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `content_readout_type` VARCHAR(64) NULL DEFAULT NULL,
  `dilution_solvent` VARCHAR(64) NULL DEFAULT NULL,
  `dilution_solvent_percent_max` FLOAT NULL DEFAULT NULL,
  `assay_component_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_component_desc` TEXT NULL DEFAULT NULL,
  `assay_component_target_desc` TEXT NULL DEFAULT NULL,
  `parameter_readout_type` VARCHAR(64) NULL DEFAULT NULL,
  `assay_design_type` VARCHAR(64) NULL DEFAULT NULL,
  `assay_design_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `biological_process_target` VARCHAR(64) NULL DEFAULT NULL,
  `detection_technology_type` VARCHAR(64) NULL DEFAULT NULL,
  `detection_technology_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `detection_technology` VARCHAR(64) NULL DEFAULT NULL,
  `signal_direction_type` VARCHAR(64) NULL DEFAULT NULL,
  `key_assay_reagent_type` VARCHAR(64) NULL DEFAULT NULL,
  `key_assay_reagent` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_type` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `assay_component_endpoINT_name` VARCHAR(64) NULL DEFAULT NULL,
  `export_ready` INT NULL DEFAULT NULL,
  `internal_ready` INT NULL DEFAULT NULL,
  `assay_component_endpoINT_desc` TEXT NULL DEFAULT NULL,
  `assay_function_type` VARCHAR(64) NULL DEFAULT NULL,
  `normalized_data_type` VARCHAR(64) NULL DEFAULT NULL,
  `analysis_direction` VARCHAR(64) NULL DEFAULT NULL,
  `burst_assay` INT NULL DEFAULT NULL,
  `key_positive_control` VARCHAR(64) NULL DEFAULT NULL,
  `signal_direction` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_type` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_family` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_family_sub` VARCHAR(64) NULL DEFAULT NULL,
  `fit_all` INT NULL DEFAULT NULL,
  `reagent_arid` VARCHAR(255) NULL DEFAULT NULL,
  `reagent_reagent_name_value` TEXT NULL DEFAULT NULL,
  `reagent_reagent_name_value_type` TEXT NULL DEFAULT NULL,
  `reagent_culture_or_assay` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`aeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Citation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Citation` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Citation` (
  `citation_id` INT NOT NULL,
  `pmid` INT NULL DEFAULT NULL,
  `doi` VARCHAR(255) NULL DEFAULT NULL,
  `other_source` VARCHAR(64) NULL DEFAULT NULL,
  `other_id` VARCHAR(64) NULL DEFAULT NULL,
  `citation` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`citation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Target` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Target` (
  `target_id` INT NOT NULL,
  `intended_target_gene_id` INT NULL DEFAULT NULL,
  `intended_target_entrez_gene_id` INT NULL DEFAULT NULL,
  `intended_target_official_full_name` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_gene_name` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_official_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_gene_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_description` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_uniprot_accession_number` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_organism_id` INT NULL DEFAULT NULL,
  `intended_target_track_status` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_gene_id` INT NULL DEFAULT NULL,
  `technological_target_entrez_gene_id` INT NULL DEFAULT NULL,
  `technological_target_official_full_name` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_gene_name` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_official_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_gene_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_description` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_uniprot_accession_number` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_organism_id` INT NULL DEFAULT NULL,
  `technological_target_track_status` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`target_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Chemicals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Chemicals` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Chemicals` (
  `DSSTox_Substance_Id` VARCHAR(64) NULL DEFAULT NULL,
  `DSSTox_Structure_Id` VARCHAR(64) NULL DEFAULT NULL,
  `DSSTox_QC-Level` VARCHAR(64) NULL DEFAULT NULL,
  `Substance_Name` VARCHAR(64) NULL DEFAULT NULL,
  `Substance_CASRN` VARCHAR(64) NOT NULL,
  `Substance_Type` VARCHAR(64) NULL DEFAULT NULL,
  `Substance_Note` VARCHAR(64) NULL DEFAULT NULL,
  `Structure_SMILES` VARCHAR(64) NULL DEFAULT NULL,
  `Structure_InChI` VARCHAR(64) NULL DEFAULT NULL,
  `Structure_InChIKey` VARCHAR(64) NULL DEFAULT NULL,
  `Structure_Formula` VARCHAR(64) NULL DEFAULT NULL,
  `Structure_MolWt` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Substance_CASRN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `level` VARCHAR(15) NOT NULL DEFAULT 'user',
  `loggedIn` TINYINT ZEROFILL NOT NULL,
  `creationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Toxicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Toxicity` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Toxicity` (
  `Substance_CASRN` VARCHAR(64) NOT NULL,
  `aeid` INT NOT NULL,
  `m4id` INT NULL DEFAULT NULL,
  `m5id` INT NULL DEFAULT NULL,
  `spid` VARCHAR(64) NULL DEFAULT NULL,
  `stkc` INT NULL DEFAULT NULL,
  `stkc_unit` VARCHAR(10) NULL DEFAULT NULL,
  `tested_conc_unit` VARCHAR(10) NULL DEFAULT NULL,
  `spid_legacy` VARCHAR(64) NULL DEFAULT NULL,
  `chid` INT NULL DEFAULT NULL,
  `casn` VARCHAR(64) NULL DEFAULT NULL,
  `chnm` VARCHAR(64) NULL DEFAULT NULL,
  `code` VARCHAR(64) NULL DEFAULT NULL,
  `aenm` VARCHAR(64) NULL DEFAULT NULL,
  `resp_unit` VARCHAR(64) NULL DEFAULT NULL,
  `nconc` INT NULL DEFAULT NULL,
  `npts` INT NULL DEFAULT NULL,
  `nmed_gtbl` INT NULL DEFAULT NULL,
  `hitc` INT NULL DEFAULT NULL,
  `modl` VARCHAR(32) NULL DEFAULT NULL,
  `fitc` INT NULL DEFAULT NULL,
  `coff` FLOAT NULL DEFAULT NULL,
  `bmad` FLOAT NULL DEFAULT NULL,
  `gsid_rep` INT NULL DEFAULT NULL,
  `chit` TINYINT NULL DEFAULT NULL,
  `flag_ids` INT NULL DEFAULT NULL,
  `flags` VARCHAR(64) NULL DEFAULT NULL,
  `resp_max` FLOAT NULL DEFAULT NULL,
  `resp_min` FLOAT NULL DEFAULT NULL,
  `max_mean` FLOAT NULL DEFAULT NULL,
  `max_mean_conc` FLOAT NULL DEFAULT NULL,
  `max_med` FLOAT NULL DEFAULT NULL,
  `max_med_conc` FLOAT NULL DEFAULT NULL,
  `logc_max` FLOAT NULL DEFAULT NULL,
  `logc_min` FLOAT NULL DEFAULT NULL,
  `actp` FLOAT NULL DEFAULT NULL,
  `modl_er` FLOAT NULL DEFAULT NULL,
  `modl_tp` FLOAT NULL DEFAULT NULL,
  `modl_ga` FLOAT NULL DEFAULT NULL,
  `modl_gw` FLOAT NULL DEFAULT NULL,
  `modl_la` FLOAT NULL DEFAULT NULL,
  `modl_lw` FLOAT NULL DEFAULT NULL,
  `modl_rmse` FLOAT NULL DEFAULT NULL,
  `modl_prob` FLOAT NULL DEFAULT NULL,
  `modl_acc` FLOAT NULL DEFAULT NULL,
  `modl_acb` FLOAT NULL DEFAULT NULL,
  `cnst` INT NULL DEFAULT NULL,
  `hill` INT NULL DEFAULT NULL,
  `hcov` INT NULL DEFAULT NULL,
  `gnls` INT NULL DEFAULT NULL,
  `gcov` INT NULL DEFAULT NULL,
  `cnst_er` FLOAT NULL DEFAULT NULL,
  `cnst_aic` FLOAT NULL DEFAULT NULL,
  `cnst_rmse` FLOAT NULL DEFAULT NULL,
  `cnst_prob` FLOAT NULL DEFAULT NULL,
  `hill_tp` FLOAT NULL DEFAULT NULL,
  `hill_tp_sd` FLOAT NULL DEFAULT NULL,
  `hill_ga` FLOAT NULL DEFAULT NULL,
  `hill_ga_sd` FLOAT NULL DEFAULT NULL,
  `hill_gw` FLOAT NULL DEFAULT NULL,
  `hill_gw_sd` FLOAT NULL DEFAULT NULL,
  `hill_er` FLOAT NULL DEFAULT NULL,
  `hill_er_sd` FLOAT NULL DEFAULT NULL,
  `hill_aic` FLOAT NULL DEFAULT NULL,
  `hill_rmse` FLOAT NULL DEFAULT NULL,
  `hill_prob` FLOAT NULL DEFAULT NULL,
  `gnls_tp` FLOAT NULL DEFAULT NULL,
  `gnls_tp_sd` FLOAT NULL DEFAULT NULL,
  `gnls_ga` FLOAT NULL DEFAULT NULL,
  `gnls_ga_sd` FLOAT NULL DEFAULT NULL,
  `gnls_gw` FLOAT NULL DEFAULT NULL,
  `gnls_gw_sd` FLOAT NULL DEFAULT NULL,
  `gnls_la` FLOAT NULL DEFAULT NULL,
  `gnls_la_sd` FLOAT NULL DEFAULT NULL,
  `gnls_lw` FLOAT NULL DEFAULT NULL,
  `gnls_lw_sd` FLOAT NULL DEFAULT NULL,
  `gnls_er` FLOAT NULL DEFAULT NULL,
  `gnls_er_sd` FLOAT NULL DEFAULT NULL,
  `gnls_aic` FLOAT NULL DEFAULT NULL,
  `gnls_rmse` FLOAT NULL DEFAULT NULL,
  `gnls_prob` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`Substance_CASRN`, `aeid`),
  INDEX `fk_Toxicity_Assay1_idx` (`aeid` ASC),
  CONSTRAINT `fk_Toxicity_Chemicals1`
    FOREIGN KEY (`Substance_CASRN`)
    REFERENCES `ChemDB`.`Chemicals` (`Substance_CASRN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Toxicity_Assay1`
    FOREIGN KEY (`aeid`)
    REFERENCES `ChemDB`.`Assay` (`aeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Published`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Published` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Published` (
  `aeid` INT NOT NULL,
  `citation_id` INT NOT NULL,
  PRIMARY KEY (`aeid`, `citation_id`),
  INDEX `fk_Published_Citation1_idx` (`citation_id` ASC),
  CONSTRAINT `fk_Published_Assay1`
    FOREIGN KEY (`aeid`)
    REFERENCES `ChemDB`.`Assay` (`aeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Published_Citation1`
    FOREIGN KEY (`citation_id`)
    REFERENCES `ChemDB`.`Citation` (`citation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Tested`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChemDB`.`Tested` ;

CREATE TABLE IF NOT EXISTS `ChemDB`.`Tested` (
  `aeid` INT NOT NULL,
  `target_id` INT NOT NULL,
  PRIMARY KEY (`aeid`, `target_id`),
  INDEX `fk_Tested_Target1_idx` (`target_id` ASC),
  CONSTRAINT `fk_Tested_Assay1`
    FOREIGN KEY (`aeid`)
    REFERENCES `ChemDB`.`Assay` (`aeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tested_Target1`
    FOREIGN KEY (`target_id`)
    REFERENCES `ChemDB`.`Target` (`target_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
