-- MySQL Script generated by MySQL Workbench
-- Wed Mar  7 07:44:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ChemDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ChemDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ChemDB` DEFAULT CHARACTER SET utf8 ;
USE `ChemDB` ;

-- -----------------------------------------------------
-- Table `ChemDB`.`Assay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChemDB`.`Assay` (
  `aid` INT NOT NULL,
  `acid` INT NOT NULL,
  `aeid` INT NOT NULL,
  `asid` INT NOT NULL,
  `assay_source_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_source_long_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_source_desc` TEXT NULL DEFAULT NULL,
  `assay_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_desc` VARCHAR(255) NULL DEFAULT NULL,
  `timepoint_hr` INT NULL DEFAULT NULL,
  `organism_id` INT NULL DEFAULT NULL,
  `organism` VARCHAR(64) NULL DEFAULT NULL,
  `tissue` VARCHAR(64) NULL DEFAULT NULL,
  `cell_format` VARCHAR(64) NULL DEFAULT NULL,
  `cell_free_component_source` VARCHAR(255) NULL DEFAULT NULL,
  `cell_short_name` VARCHAR(64) NULL DEFAULT NULL,
  `cell_growth_mode` VARCHAR(64) NULL DEFAULT NULL,
  `assay_footprINT` VARCHAR(64) NULL DEFAULT NULL,
  `assay_format_type` VARCHAR(64) NULL DEFAULT NULL,
  `assay_format_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `content_readout_type` VARCHAR(64) NULL DEFAULT NULL,
  `dilution_solvent` VARCHAR(64) NULL DEFAULT NULL,
  `dilution_solvent_percent_max` FLOAT NULL DEFAULT NULL,
  `assay_component_name` VARCHAR(64) NULL DEFAULT NULL,
  `assay_component_desc` TEXT NULL DEFAULT NULL,
  `assay_component_target_desc` TEXT NULL DEFAULT NULL,
  `parameter_readout_type` VARCHAR(64) NULL DEFAULT NULL,
  `assay_design_type` VARCHAR(64) NULL DEFAULT NULL,
  `assay_design_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `biological_process_target` VARCHAR(64) NULL DEFAULT NULL,
  `detection_technology_type` VARCHAR(64) NULL DEFAULT NULL,
  `detection_technology_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `detection_technology` VARCHAR(64) NULL DEFAULT NULL,
  `signal_direction_type` VARCHAR(64) NULL DEFAULT NULL,
  `key_assay_reagent_type` VARCHAR(64) NULL DEFAULT NULL,
  `key_assay_reagent` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_type` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `assay_component_endpoINT_name` VARCHAR(64) NULL DEFAULT NULL,
  `export_ready` INT NULL DEFAULT NULL,
  `internal_ready` INT NULL DEFAULT NULL,
  `assay_component_endpoINT_desc` TEXT NULL DEFAULT NULL,
  `assay_function_type` VARCHAR(64) NULL DEFAULT NULL,
  `normalized_data_type` VARCHAR(64) NULL DEFAULT NULL,
  `analysis_direction` VARCHAR(64) NULL DEFAULT NULL,
  `burst_assay` INT NULL DEFAULT NULL,
  `key_positive_control` VARCHAR(64) NULL DEFAULT NULL,
  `signal_direction` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_type` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_type_sub` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_family` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_family_sub` VARCHAR(64) NULL DEFAULT NULL,
  `fit_all` INT NULL DEFAULT NULL,
  `reagent_arid` VARCHAR(255) NULL DEFAULT NULL,
  `reagent_reagent_name_value` TEXT NULL DEFAULT NULL,
  `reagent_reagent_name_value_type` TEXT NULL DEFAULT NULL,
  `reagent_culture_or_assay` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`aid`, `acid`, `aeid`, `asid`));


-- -----------------------------------------------------
-- Table `ChemDB`.`Citation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChemDB`.`Citation` (
  `citation_id` INT NOT NULL,
  `pmid` INT NOT NULL,
  `doi` VARCHAR(255) NULL DEFAULT NULL,
  `other_source` VARCHAR(64) NULL DEFAULT NULL,
  `other_id` VARCHAR(64) NULL DEFAULT NULL,
  `citation` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(64) NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`citation_id`, `pmid`));


-- -----------------------------------------------------
-- Table `ChemDB`.`Target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChemDB`.`Target` (
  `target_id` INT NOT NULL,
  `intended_target_gene_id` INT NULL DEFAULT NULL,
  `intended_target_entrez_gene_id` INT NULL DEFAULT NULL,
  `intended_target_official_full_name` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_gene_name` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_official_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_gene_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_description` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_uniprot_accession_number` VARCHAR(64) NULL DEFAULT NULL,
  `intended_target_organism_id` INT NULL DEFAULT NULL,
  `intended_target_track_status` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_gene_id` INT NULL DEFAULT NULL,
  `technological_target_entrez_gene_id` INT NULL DEFAULT NULL,
  `technological_target_official_full_name` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_gene_name` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_official_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_gene_symbol` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_description` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_uniprot_accession_number` VARCHAR(64) NULL DEFAULT NULL,
  `technological_target_organism_id` INT NULL DEFAULT NULL,
  `technological_target_track_status` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`target_id`));


-- -----------------------------------------------------
-- Table `ChemDB`.`Published`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChemDB`.`Published` (
  `Citation_citation_id` INT NOT NULL,
  `Citation_pmid` INT NOT NULL,
  `Assay_aeid` INT NOT NULL,
  PRIMARY KEY (`Assay_aeid`, `Citation_pmid`, `Citation_citation_id`),
  INDEX `fk_Published_Citation1_idx` (`Citation_citation_id` ASC, `Citation_pmid` ASC),
  INDEX `fk_Published_Assay1_idx` (`Assay_aeid` ASC),
  CONSTRAINT `fk_Published_Citation1`
    FOREIGN KEY (`Citation_citation_id` , `Citation_pmid`)
    REFERENCES `ChemDB`.`Citation` (`citation_id` , `pmid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Published_Assay1`
    FOREIGN KEY (`Assay_aeid`)
    REFERENCES `ChemDB`.`Assay` (`aeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChemDB`.`Tested`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ChemDB`.`Tested` (
  `Target_target_id` INT NOT NULL,
  `Assay_aeid` INT NOT NULL,
  PRIMARY KEY (`Target_target_id`, `Assay_aeid`),
  INDEX `fk_Tested_Target1_idx` (`Target_target_id` ASC),
  INDEX `fk_Tested_Assay1_idx` (`Assay_aeid` ASC),
  CONSTRAINT `fk_Tested_Target1`
    FOREIGN KEY (`Target_target_id`)
    REFERENCES `ChemDB`.`Target` (`target_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tested_Assay1`
    FOREIGN KEY (`Assay_aeid`)
    REFERENCES `ChemDB`.`Assay` (`aeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
